### ISSUE TITLE
“FileNotFoundError: [Errno 2] No such file or directory: '../data/scenes/scene-0061/depth'”

### ISSUE THREAD

**Issue by rockywind** [fudan-zvg/S-NeRF#3]
Hi，thank you for sharing the great work!
I met the error when I run the training code.
````
python s-nerf/train_my.py --config s-nerf/configs/nuScenes_rgb_6cams
````
The error is below.
````
    img_files = sorted(os.listdir(imgdir), key=lambda x : int(x.split('.')[0]))
FileNotFoundError: [Errno 2] No such file or directory: '../data/scenes/scene-0061/depth'
````

**Comment by raja-kumar** [comment]
@rockywind I face the same issue. The data processing script doesn't create depth data. However, it is required during training. Did you figure this out?

**Comment by amoghskanda** [comment]
After many modifications to `YORO_1CAM_PIPELINE_REFINE.py` I was able to generate depth data but it gets stored in S-NeRF/scripts/depth_model/output/6cam_depth_data. Should there be any changes to the path in the configs?

**Comment by emjay73** [comment]
I have a same problem as @amoghskanda
