### ISSUE TITLE
nuScenes eval scenes

### ISSUE THREAD

**Issue by georghess** [fudan-zvg/S-NeRF#9]
Hi! Thanks for this nice work :) 

Which nuScenes sequences did you use for evaluation? The paper says 4 sequences were used, but I could not find which ones.

**Comment by ZiYang-xie** [comment]
Hi, we evaluated our model using following 4 scenes.
- scene-0164
- scene-0209
- scene-0359
- scene-0916

You may test your model on these scenes and benchmark its performance against ours. We hope our findings prove beneficial for your own research.

Please don't hesitate to reach out if you require further assistance.

**Comment by EhabWilson** [comment]
@ZiYang-xie Thanks for releasing eval scenes!
Can you provide more details :
+ which frames did you use to train model?
+ Is half-train needed?
+ what config did you use to train, all the scenes are the same as s-nerf/configs/*?

**Comment by git-sachin1066** [comment]
Hello, very reasonable question..
@EhabWilson @ZiYang-xie , any info on this  https://github.com/fudan-zvg/S-NeRF/issues/9#issuecomment-1779114214??
